// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// wordcloud_boxes
DataFrame wordcloud_boxes(NumericMatrix data_points, NumericMatrix boxes, IntegerVector boxes_text, IntegerMatrix text_boxes, NumericVector xlim, NumericVector ylim, double eccentricity, double rstep, double tstep);
RcppExport SEXP _ggwordcloud_wordcloud_boxes(SEXP data_pointsSEXP, SEXP boxesSEXP, SEXP boxes_textSEXP, SEXP text_boxesSEXP, SEXP xlimSEXP, SEXP ylimSEXP, SEXP eccentricitySEXP, SEXP rstepSEXP, SEXP tstepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data_points(data_pointsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type boxes(boxesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type boxes_text(boxes_textSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type text_boxes(text_boxesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xlim(xlimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ylim(ylimSEXP);
    Rcpp::traits::input_parameter< double >::type eccentricity(eccentricitySEXP);
    Rcpp::traits::input_parameter< double >::type rstep(rstepSEXP);
    Rcpp::traits::input_parameter< double >::type tstep(tstepSEXP);
    rcpp_result_gen = Rcpp::wrap(wordcloud_boxes(data_points, boxes, boxes_text, text_boxes, xlim, ylim, eccentricity, rstep, tstep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ggwordcloud_wordcloud_boxes", (DL_FUNC) &_ggwordcloud_wordcloud_boxes, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_ggwordcloud(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
