# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wordcloud_boxes <- function(data_points, boxes, boxes_text, text_boxes, xlim, ylim, eccentricity = 0.65, rstep = 0.1, tstep = 0.05, percstep = 0.1, maxsteps = 10L, rm_outside = FALSE) {
    .Call(`_ggwordcloud_wordcloud_boxes`, data_points, boxes, boxes_text, text_boxes, xlim, ylim, eccentricity, rstep, tstep, percstep, maxsteps, rm_outside)
}

