# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wordcloud_boxes <- function(data_points, boxes, boxes_text, text_boxes, bigboxes, xlim, ylim, eccentricity = 0.65, rstep = 0.1, tstep = 0.05, perc_step = 0.01, max_steps = 10L, rm_outside = FALSE, shape = 1L) {
    .Call(`_ggwordcloud_wordcloud_boxes`, data_points, boxes, boxes_text, text_boxes, bigboxes, xlim, ylim, eccentricity, rstep, tstep, perc_step, max_steps, rm_outside, shape)
}

